name: flutter_chat_firebase
description: "Flutter chat firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  crypto: ^3.0.3
  webview_flutter: ^4.4.4
  loading_animations: ^2.2.0
  # share
  share: ^2.0.4
  # 设备信息
  device_info: ^2.0.3
  # 包信息
  package_info: ^2.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  sentry: ^7.14.0
  uni_links: ^0.5.1
  flutter_spinkit: ^5.2.0
  #flutter_swiper: ^1.1.6
  dots_indicator: ^3.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_in_app_messaging: ^0.7.4+8
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  location: ^5.0.3
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_cupertino_localizations: ^1.0.1
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
